[[weapon]]
id = 2
name = "木剑"
level = 1
description = """用木头制成的朴素长剑。实在难以称之为刀具，
然而木材对魔力的传导力比矿物更强，因此也不能小觑。"""
price = 150
equip_type = 1
weapon_type = 1
atk = 'medium'
mat = 'very_high'

[[weapon]]
id = 3
name = "青铜剑"
level = 2
description = "铜制的粗糙剑具。"
price = 300
equip_type = 1
weapon_type = 1
atk = 'high'
mat = 'low'

[[weapon]]
id = 4
name = "魔铜剑"
level = 2
description = """本身被赋予了魔法的剑，拥有与杖不相上下的魔力。
如果志愿成为魔剑士的话，无论如何都应该试着去挥舞它一次。"""
price = 480
equip_type = 1
weapon_type = 1
atk = 'low'
mat = 'high'

[[weapon]]
id = 5
name = "铁剑"
level = 3
description = "用铁打造出来的普通长剑。"
price = 400
equip_type = 1
weapon_type = 1
atk = 'high'
mat = 'low'

[[weapon]]
id = 6
name = "护手刺剑"
level = 4
description = """由工匠打造出来的细长而精致的刺剑。
空出来的另一只手也可以再拿一把武器。"""
price = 700
equip_type = 1
weapon_type = 1
atk = 'medium'
mat = 'medium'

[[weapon]]
id = 7
name = "卢恩剑"
level = 4
description = """用卢恩木制成的木剑。
会对我方的魔法产生反应，以魔光刃追击敌人。"""
price = 640
equip_type = 1
weapon_type = 1
atk = 'low'
mat = 'high'

[[weapon]]
id = 8
name = "亚汀剑"
level = 4
description = "亚汀社出品的轻巧而坚韧的锋利刀剑。"
price = 640
equip_type = 1
weapon_type = 1
atk = 'high'
mat = 'low'

[[weapon]]
id = 9
name = "秘银剑"
level = 5
description = """为退魔勇者设计的圣银剑。拥有划破缠身的黑暗，反击魔法的力量。
然而，由于银矿无法作为魔力的媒介，所以不能用魔攻力来辅助使用。"""
price = 900
equip_type = 1
weapon_type = 1
atk = 'best'

[[weapon]]
id = 10
name = "月之木剑"
level = 5
description = "充满了明月魔力的木制魔法剑。"
price = 540
equip_type = 1
weapon_type = 1
atk = 'medium'
mat = 'high'

[[weapon]]
id = 11
name = "魔法剑"
level = 6
description = """用魔铁打造的强力剑器。
在战斗中将其当做普通的剑来使用也很有效，非常易用。"""
price = 1000
equip_type = 1
weapon_type = 1
atk = 'high'
mat = 'high'

[[weapon]]
id = 12
name = "黑暗剑"
level = 6
description = """被注入了魔力的不详之剑。
魔鬼中的将军若不持有一把这种等级的武器，可是会被部下小瞧的。"""
price = 1400
equip_type = 1
weapon_type = 1
atk = 'high'
mat = 'very_high'
